/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u70791707105
 */
public class JDlgWklsUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWklsUsuario
     */
    public JDlgWklsUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de usuário.");
        setLocationRelativeTo(null);
        
        jTxtWklsNome.setEnabled(false);
        JTxtWklsCodigo.setEnabled(false);
        jTxtWklsApelido.setEnabled(false);
        jFmtWklsCPF.setEnabled(false);
        jFmtWklsDataNascimento.setEnabled(false);
        jCboWklsNivel.setEnabled(false);
        jPwfWklsSenha.setEnabled(false);
        jChbWklsAtivo.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
    }
    
    public void habilitar() {
        jTxtWklsNome.setEnabled(true);
        JTxtWklsCodigo.setEnabled(true);
        jTxtWklsApelido.setEnabled(true);
        jFmtWklsCPF.setEnabled(true);
        jFmtWklsDataNascimento.setEnabled(true);
        jCboWklsNivel.setEnabled(true);
        jPwfWklsSenha.setEnabled(true);
        jChbWklsAtivo.setEnabled(true);
        jBtnWklsCancelar.setEnabled(true);
        jBtnWklsConfirmar.setEnabled(true);
        jBtnWklsIncluir.setEnabled(false);
        jBtnWklsAlterar.setEnabled(false);
        jBtnWklsExcluir.setEnabled(false);
        jBtnWklsPesquisar.setEnabled(false);
    }
    
    public void desabilitar() {
        jTxtWklsNome.setEnabled(false);
        JTxtWklsCodigo.setEnabled(false);
        jTxtWklsApelido.setEnabled(false);
        jFmtWklsCPF.setEnabled(false);
        jFmtWklsDataNascimento.setEnabled(false);
        jCboWklsNivel.setEnabled(false);
        jPwfWklsSenha.setEnabled(false);
        jChbWklsAtivo.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
        jBtnWklsIncluir.setEnabled(true);
        jBtnWklsAlterar.setEnabled(true);
        jBtnWklsExcluir.setEnabled(true);
        jBtnWklsPesquisar.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblWklsCodigo = new javax.swing.JLabel();
        JTxtWklsCodigo = new javax.swing.JTextField();
        jLblWklsNome = new javax.swing.JLabel();
        jTxtWklsNome = new javax.swing.JTextField();
        jLblWklsApelido = new javax.swing.JLabel();
        jTxtWklsApelido = new javax.swing.JTextField();
        jLblWklsNivel = new javax.swing.JLabel();
        jCboWklsNivel = new javax.swing.JComboBox<>();
        jLblWklsCpf = new javax.swing.JLabel();
        jFmtWklsCPF = new javax.swing.JTextField();
        jLblWklsDataDeNascimento = new javax.swing.JLabel();
        jFmtWklsDataNascimento = new javax.swing.JTextField();
        jLblWklsSenha = new javax.swing.JLabel();
        jPwfWklsSenha = new javax.swing.JPasswordField();
        jChbWklsAtivo = new javax.swing.JCheckBox();
        jBtnWklsCancelar = new javax.swing.JButton();
        jBtnWklsConfirmar = new javax.swing.JButton();
        jBtnWklsPesquisar = new javax.swing.JButton();
        jBtnWklsIncluir = new javax.swing.JButton();
        jBtnWklsAlterar = new javax.swing.JButton();
        jBtnWklsExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblWklsCodigo.setText("Código :");

        JTxtWklsCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtWklsCodigoActionPerformed(evt);
            }
        });

        jLblWklsNome.setText("Nome :");

        jTxtWklsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNomeActionPerformed(evt);
            }
        });

        jLblWklsApelido.setText("Apelido :");

        jTxtWklsApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsApelidoActionPerformed(evt);
            }
        });

        jLblWklsNivel.setText("Nível :");

        jCboWklsNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblWklsCpf.setText("CPF :");

        jLblWklsDataDeNascimento.setText("Data de Nascimento :");

        jFmtWklsDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtWklsDataNascimentoActionPerformed(evt);
            }
        });

        jLblWklsSenha.setText("Senha :");

        jPwfWklsSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwfWklsSenhaActionPerformed(evt);
            }
        });

        jChbWklsAtivo.setText("Ativo");
        jChbWklsAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbWklsAtivoActionPerformed(evt);
            }
        });

        jBtnWklsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWklsCancelar.setText("Cancelar");
        jBtnWklsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsCancelarActionPerformed(evt);
            }
        });

        jBtnWklsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnWklsConfirmar.setText("Confirmar");
        jBtnWklsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsConfirmarActionPerformed(evt);
            }
        });

        jBtnWklsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWklsPesquisar.setText("Pesquisar");
        jBtnWklsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsPesquisarActionPerformed(evt);
            }
        });

        jBtnWklsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWklsIncluir.setText("Incluir");
        jBtnWklsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsIncluirActionPerformed(evt);
            }
        });

        jBtnWklsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWklsAlterar.setText("Alterar");
        jBtnWklsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsAlterarActionPerformed(evt);
            }
        });

        jBtnWklsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWklsExcluir.setText("Excluir");
        jBtnWklsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPwfWklsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jChbWklsAtivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsCodigo)
                        .addGap(62, 62, 62)
                        .addComponent(jLblWklsNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsDataDeNascimento)
                        .addGap(74, 74, 74)
                        .addComponent(jLblWklsNivel))
                    .addComponent(jLblWklsSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmtWklsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCboWklsNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTxtWklsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtWklsNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtWklsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblWklsApelido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsCpf)
                            .addComponent(jFmtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnWklsIncluir)
                .addGap(27, 27, 27)
                .addComponent(jBtnWklsAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsConfirmar)
                .addGap(29, 29, 29)
                .addComponent(jBtnWklsPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsCodigo)
                    .addComponent(jLblWklsNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtWklsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsApelido)
                    .addComponent(jLblWklsCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWklsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsDataDeNascimento)
                    .addComponent(jLblWklsNivel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtWklsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboWklsNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLblWklsSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPwfWklsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbWklsAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnWklsIncluir)
                    .addComponent(jBtnWklsAlterar)
                    .addComponent(jBtnWklsExcluir)
                    .addComponent(jBtnWklsCancelar)
                    .addComponent(jBtnWklsConfirmar)
                    .addComponent(jBtnWklsPesquisar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtWklsCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtWklsCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtWklsCodigoActionPerformed

    private void jTxtWklsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNomeActionPerformed

    private void jTxtWklsApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsApelidoActionPerformed

    private void jFmtWklsDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtWklsDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtWklsDataNascimentoActionPerformed

    private void jChbWklsAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbWklsAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbWklsAtivoActionPerformed

    private void jPwfWklsSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwfWklsSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwfWklsSenhaActionPerformed

    private void jBtnWklsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsCancelarActionPerformed

    private void jBtnWklsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsConfirmarActionPerformed

    private void jBtnWklsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do Usuario:");
    }//GEN-LAST:event_jBtnWklsPesquisarActionPerformed

    private void jBtnWklsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsIncluirActionPerformed

    private void jBtnWklsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsAlterarActionPerformed

    private void jBtnWklsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
            "Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnWklsExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWklsUsuario dialog = new JDlgWklsUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtWklsCodigo;
    private javax.swing.JButton jBtnWklsAlterar;
    private javax.swing.JButton jBtnWklsCancelar;
    private javax.swing.JButton jBtnWklsConfirmar;
    private javax.swing.JButton jBtnWklsExcluir;
    private javax.swing.JButton jBtnWklsIncluir;
    private javax.swing.JButton jBtnWklsPesquisar;
    private javax.swing.JComboBox<String> jCboWklsNivel;
    private javax.swing.JCheckBox jChbWklsAtivo;
    private javax.swing.JTextField jFmtWklsCPF;
    private javax.swing.JTextField jFmtWklsDataNascimento;
    private javax.swing.JLabel jLblWklsApelido;
    private javax.swing.JLabel jLblWklsCodigo;
    private javax.swing.JLabel jLblWklsCpf;
    private javax.swing.JLabel jLblWklsDataDeNascimento;
    private javax.swing.JLabel jLblWklsNivel;
    private javax.swing.JLabel jLblWklsNome;
    private javax.swing.JLabel jLblWklsSenha;
    private javax.swing.JPasswordField jPwfWklsSenha;
    private javax.swing.JTextField jTxtWklsApelido;
    private javax.swing.JTextField jTxtWklsNome;
    // End of variables declaration//GEN-END:variables
}
