/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u70791707105
 */
public class JDlgWklsVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWklsVendedor
     */
    public JDlgWklsVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
         jTxtWklsNome.setEnabled(false);
        jTxtWklsCategoria.setEnabled(false);
        jTxtWklsCPF.setEnabled(false);
        jFmtWklsEmail.setEnabled(false);
        jTxtWklsDataContratado.setEnabled(false);
        jTxtWklsStatus.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
    }
    
    public void habilitar(){
        jTxtWklsNome.setEnabled(true);
        jTxtWklsCategoria.setEnabled(true);
        jTxtWklsCPF.setEnabled(true);
        jFmtWklsEmail.setEnabled(true);
        jTxtWklsDataContratado.setEnabled(true);
        jTxtWklsStatus.setEnabled(true);
        jBtnWklsCancelar.setEnabled(true);
        jBtnWklsConfirmar.setEnabled(true);
          jBtnWklsIncluir.setEnabled(false);
        jBtnWklsAlterar.setEnabled(false);
        jBtnWklsExcluir.setEnabled(false);
        jBtnWklsPesquisar.setEnabled(false);
    }
    
    public void desabilitar(){
        jTxtWklsNome.setEnabled(false);
        jTxtWklsCategoria.setEnabled(false);
        jTxtWklsCPF.setEnabled(false);
        jFmtWklsEmail.setEnabled(false);
        jTxtWklsDataContratado.setEnabled(false);
        jTxtWklsStatus.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
          jBtnWklsIncluir.setEnabled(true);
        jBtnWklsAlterar.setEnabled(true);
        jBtnWklsExcluir.setEnabled(true);
        jBtnWklsPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblWklsTelefone = new javax.swing.JLabel();
        jLblWklsCpf = new javax.swing.JLabel();
        jBtnWklsConfirmar = new javax.swing.JButton();
        jFmtWklsEmail = new javax.swing.JTextField();
        jLblWklsEmail = new javax.swing.JLabel();
        jBtnWklsPesquisar = new javax.swing.JButton();
        jTxtWklsNome = new javax.swing.JTextField();
        jBtnWklsIncluir = new javax.swing.JButton();
        jLblWklsRg = new javax.swing.JLabel();
        jBtnWklsAlterar = new javax.swing.JButton();
        jTxtWklsCategoria = new javax.swing.JTextField();
        jBtnWklsExcluir = new javax.swing.JButton();
        jBtnWklsCancelar = new javax.swing.JButton();
        jTxtWklsDataContratado = new javax.swing.JTextField();
        jTxtWklsCPF = new javax.swing.JTextField();
        jLblWklsBairro = new javax.swing.JLabel();
        jLblWklsNome = new javax.swing.JLabel();
        jTxtWklsStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblWklsTelefone.setText("CPF:");

        jLblWklsCpf.setText("Email:");

        jBtnWklsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnWklsConfirmar.setText("Confirmar");
        jBtnWklsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsConfirmarActionPerformed(evt);
            }
        });

        jLblWklsEmail.setText("Data da Contratação:");

        jBtnWklsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWklsPesquisar.setText("Pesquisar");
        jBtnWklsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsPesquisarActionPerformed(evt);
            }
        });

        jTxtWklsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNomeActionPerformed(evt);
            }
        });

        jBtnWklsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWklsIncluir.setText("Incluir");
        jBtnWklsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsIncluirActionPerformed(evt);
            }
        });

        jLblWklsRg.setText("Telefone:");

        jBtnWklsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWklsAlterar.setText("Alterar");
        jBtnWklsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsAlterarActionPerformed(evt);
            }
        });

        jTxtWklsCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsCategoriaActionPerformed(evt);
            }
        });

        jBtnWklsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWklsExcluir.setText("Excluir");
        jBtnWklsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsExcluirActionPerformed(evt);
            }
        });

        jBtnWklsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWklsCancelar.setText("Cancelar");
        jBtnWklsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsCancelarActionPerformed(evt);
            }
        });

        jTxtWklsCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsCPFActionPerformed(evt);
            }
        });

        jLblWklsBairro.setText("Status:");

        jLblWklsNome.setText("Nome :");

        jTxtWklsStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsStatusActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtWklsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblWklsRg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsCpf)
                            .addComponent(jFmtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLblWklsEmail))
                            .addComponent(jTxtWklsDataContratado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLblWklsBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBtnWklsIncluir)
                                .addGap(27, 27, 27)
                                .addComponent(jBtnWklsAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnWklsExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnWklsCancelar)))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnWklsConfirmar)
                        .addGap(29, 29, 29)
                        .addComponent(jBtnWklsPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsNome)
                            .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsTelefone)
                            .addComponent(jTxtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxtWklsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsDataContratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsRg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblWklsCpf)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jFmtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblWklsBairro)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtWklsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnWklsIncluir)
                    .addComponent(jBtnWklsAlterar)
                    .addComponent(jBtnWklsExcluir)
                    .addComponent(jBtnWklsCancelar)
                    .addComponent(jBtnWklsConfirmar)
                    .addComponent(jBtnWklsPesquisar))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnWklsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsConfirmarActionPerformed

    private void jTxtWklsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNomeActionPerformed

    private void jBtnWklsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsIncluirActionPerformed

    private void jBtnWklsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsAlterarActionPerformed

    private void jTxtWklsCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsCategoriaActionPerformed

    private void jBtnWklsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsCancelarActionPerformed

    private void jTxtWklsCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsCPFActionPerformed

    private void jTxtWklsStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsStatusActionPerformed

    private void jBtnWklsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnWklsExcluirActionPerformed

    private void jBtnWklsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do Vendedor:");
    }//GEN-LAST:event_jBtnWklsPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWklsVendedor dialog = new JDlgWklsVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWklsAlterar;
    private javax.swing.JButton jBtnWklsCancelar;
    private javax.swing.JButton jBtnWklsConfirmar;
    private javax.swing.JButton jBtnWklsExcluir;
    private javax.swing.JButton jBtnWklsIncluir;
    private javax.swing.JButton jBtnWklsPesquisar;
    private javax.swing.JTextField jFmtWklsEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblWklsBairro;
    private javax.swing.JLabel jLblWklsCpf;
    private javax.swing.JLabel jLblWklsEmail;
    private javax.swing.JLabel jLblWklsNome;
    private javax.swing.JLabel jLblWklsRg;
    private javax.swing.JLabel jLblWklsTelefone;
    private javax.swing.JTextField jTxtWklsCPF;
    private javax.swing.JTextField jTxtWklsCategoria;
    private javax.swing.JTextField jTxtWklsDataContratado;
    private javax.swing.JTextField jTxtWklsNome;
    private javax.swing.JTextField jTxtWklsStatus;
    // End of variables declaration//GEN-END:variables
}
