/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u70791707105
 */
public class JDlgWklsClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWklsClientes
     */
    public JDlgWklsClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes.");
        setLocationRelativeTo(null);
        jTxtWklsNome.setEnabled(false);
        jTxtWklsTelefone.setEnabled(false);
        jSpnWklsIdade.setEnabled(false);
        jTxtWklsRg.setEnabled(false);
        jFmtWklsCPF.setEnabled(false);
        jTxtWklsEmail.setEnabled(false);
        jCboWklsSexo.setEnabled(false);
        jTxtWklsCep.setEnabled(false);
        jTxtWklsBairro.setEnabled(false);
        jFmtWklsDataNascimento.setEnabled(false);
        jTxtWklsRua.setEnabled(false);
        jTxtWklsNumero.setEnabled(false);
        jTxtWklsCidade.setEnabled(false);
        jTxtWklsEstado.setEnabled(false);
        jChbWklsAtivo.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
    }
    
    public void habilitar() {
        jTxtWklsNome.setEnabled(true);
        jTxtWklsTelefone.setEnabled(true);
        jSpnWklsIdade.setEnabled(true);
        jTxtWklsRg.setEnabled(true);
        jFmtWklsCPF.setEnabled(true);
        jTxtWklsEmail.setEnabled(true);
        jCboWklsSexo.setEnabled(true);
        jTxtWklsCep.setEnabled(true);
        jTxtWklsBairro.setEnabled(true);
        jFmtWklsDataNascimento.setEnabled(true);
        jTxtWklsRua.setEnabled(true);
        jTxtWklsNumero.setEnabled(true);
        jTxtWklsCidade.setEnabled(true);
        jTxtWklsEstado.setEnabled(true);
        jChbWklsAtivo.setEnabled(true);
        jBtnWklsCancelar.setEnabled(true);
        jBtnWklsConfirmar.setEnabled(true);
        jBtnWklsIncluir.setEnabled(false);
        jBtnWklsAlterar.setEnabled(false);
        jBtnWklsExcluir.setEnabled(false);
        jBtnWklsPesquisar.setEnabled(false);
    }
    
    public void desabilitar() {
        jTxtWklsNome.setEnabled(false);
        jTxtWklsTelefone.setEnabled(false);
        jSpnWklsIdade.setEnabled(false);
        jTxtWklsRg.setEnabled(false);
        jFmtWklsCPF.setEnabled(false);
        jTxtWklsEmail.setEnabled(false);
        jCboWklsSexo.setEnabled(false);
        jTxtWklsCep.setEnabled(false);
        jTxtWklsBairro.setEnabled(false);
        jFmtWklsDataNascimento.setEnabled(false);
        jTxtWklsRua.setEnabled(false);
        jTxtWklsNumero.setEnabled(false);
        jTxtWklsCidade.setEnabled(false);
        jTxtWklsEstado.setEnabled(false);
        jChbWklsAtivo.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
        jBtnWklsIncluir.setEnabled(true);
        jBtnWklsAlterar.setEnabled(true);
        jBtnWklsExcluir.setEnabled(true);
        jBtnWklsPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFmtWklsCPF = new javax.swing.JTextField();
        jLblWklsDataDeNascimento = new javax.swing.JLabel();
        jLblWklsIdade = new javax.swing.JLabel();
        jChbWklsAtivo = new javax.swing.JCheckBox();
        jLblWklsTelefone = new javax.swing.JLabel();
        jTxtWklsTelefone = new javax.swing.JTextField();
        jLblWklsNome = new javax.swing.JLabel();
        jTxtWklsNome = new javax.swing.JTextField();
        jLblWklsRg = new javax.swing.JLabel();
        jTxtWklsRg = new javax.swing.JTextField();
        jLblWklsSexo = new javax.swing.JLabel();
        jCboWklsSexo = new javax.swing.JComboBox<>();
        jLblWklsCpf = new javax.swing.JLabel();
        jSpnWklsIdade = new javax.swing.JSpinner();
        jTxtWklsCep = new javax.swing.JTextField();
        jLblWklsCep = new javax.swing.JLabel();
        jLblWklsEmail = new javax.swing.JLabel();
        jTxtWklsEmail = new javax.swing.JTextField();
        jLblWklsBairro = new javax.swing.JLabel();
        jTxtWklsBairro = new javax.swing.JTextField();
        jLblWklsRua = new javax.swing.JLabel();
        jTxtWklsRua = new javax.swing.JTextField();
        jLblWklsNumero = new javax.swing.JLabel();
        jTxtWklsNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtWklsCidade = new javax.swing.JTextField();
        jLblWklsEstado = new javax.swing.JLabel();
        jTxtWklsEstado = new javax.swing.JTextField();
        jFmtWklsDataNascimento = new javax.swing.JFormattedTextField();
        jBtnWklsCancelar = new javax.swing.JButton();
        jBtnWklsConfirmar = new javax.swing.JButton();
        jBtnWklsPesquisar = new javax.swing.JButton();
        jBtnWklsIncluir = new javax.swing.JButton();
        jBtnWklsAlterar = new javax.swing.JButton();
        jBtnWklsExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblWklsDataDeNascimento.setText("Data de Nascimento :");

        jLblWklsIdade.setText("Idade :");

        jChbWklsAtivo.setText("Ativo");
        jChbWklsAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbWklsAtivoActionPerformed(evt);
            }
        });

        jLblWklsTelefone.setText("Telefone : ");

        jTxtWklsTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsTelefoneActionPerformed(evt);
            }
        });

        jLblWklsNome.setText("Nome :");

        jTxtWklsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNomeActionPerformed(evt);
            }
        });

        jLblWklsRg.setText("Rg : ");

        jTxtWklsRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsRgActionPerformed(evt);
            }
        });

        jLblWklsSexo.setText("Sexo : ");

        jCboWklsSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboWklsSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboWklsSexoActionPerformed(evt);
            }
        });

        jLblWklsCpf.setText("CPF :");

        jTxtWklsCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsCepActionPerformed(evt);
            }
        });

        jLblWklsCep.setText("Cep :");

        jLblWklsEmail.setText("Email :");

        jLblWklsBairro.setText("Bairro :");

        jTxtWklsBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsBairroActionPerformed(evt);
            }
        });

        jLblWklsRua.setText("Rua :");

        jTxtWklsRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsRuaActionPerformed(evt);
            }
        });

        jLblWklsNumero.setText("Número :");

        jTxtWklsNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNumeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Cidade :");

        jLblWklsEstado.setText("Estado :");

        jBtnWklsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWklsCancelar.setText("Cancelar");
        jBtnWklsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsCancelarActionPerformed(evt);
            }
        });

        jBtnWklsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnWklsConfirmar.setText("Confirmar");
        jBtnWklsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsConfirmarActionPerformed(evt);
            }
        });

        jBtnWklsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWklsPesquisar.setText("Pesquisar");
        jBtnWklsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsPesquisarActionPerformed(evt);
            }
        });

        jBtnWklsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWklsIncluir.setText("Incluir");
        jBtnWklsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsIncluirActionPerformed(evt);
            }
        });

        jBtnWklsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWklsAlterar.setText("Alterar");
        jBtnWklsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsAlterarActionPerformed(evt);
            }
        });

        jBtnWklsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWklsExcluir.setText("Excluir");
        jBtnWklsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jFmtWklsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsRua)
                            .addGap(269, 269, 269))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblWklsSexo)
                                .addComponent(jCboWklsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtWklsCep, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblWklsCep))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblWklsBairro)
                                .addComponent(jTxtWklsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsDataDeNascimento)
                            .addGap(24, 24, 24)
                            .addComponent(jLblWklsRua))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtWklsRg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblWklsRg))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblWklsCpf)
                                .addComponent(jFmtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLblWklsEmail))
                                .addComponent(jTxtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(534, 534, 534)
                            .addComponent(jChbWklsAtivo))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblWklsNumero)
                                .addComponent(jTxtWklsNumero))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(246, 246, 246)
                                    .addComponent(jLblWklsEstado))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtWklsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtWklsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsNome)
                            .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsTelefone)
                            .addComponent(jTxtWklsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpnWklsIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblWklsIdade))
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnWklsIncluir)
                .addGap(27, 27, 27)
                .addComponent(jBtnWklsAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnWklsConfirmar)
                .addGap(29, 29, 29)
                .addComponent(jBtnWklsPesquisar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtWklsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpnWklsIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsRg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblWklsCpf)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jFmtWklsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboWklsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsCep)
                            .addComponent(jLblWklsBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtWklsCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtWklsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsDataDeNascimento)
                    .addComponent(jLblWklsRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWklsRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtWklsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsNumero)
                    .addComponent(jLabel1)
                    .addComponent(jLblWklsEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWklsNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChbWklsAtivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnWklsIncluir)
                    .addComponent(jBtnWklsAlterar)
                    .addComponent(jBtnWklsExcluir)
                    .addComponent(jBtnWklsCancelar)
                    .addComponent(jBtnWklsConfirmar)
                    .addComponent(jBtnWklsPesquisar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChbWklsAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbWklsAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbWklsAtivoActionPerformed

    private void jTxtWklsTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsTelefoneActionPerformed

    private void jTxtWklsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNomeActionPerformed

    private void jTxtWklsRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsRgActionPerformed

    private void jCboWklsSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboWklsSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboWklsSexoActionPerformed

    private void jTxtWklsCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsCepActionPerformed

    private void jTxtWklsBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsBairroActionPerformed

    private void jTxtWklsRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsRuaActionPerformed

    private void jTxtWklsNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNumeroActionPerformed

    private void jBtnWklsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsCancelarActionPerformed

    private void jBtnWklsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsConfirmarActionPerformed

    private void jBtnWklsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do Cliente:");
    }//GEN-LAST:event_jBtnWklsPesquisarActionPerformed

    private void jBtnWklsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsIncluirActionPerformed

    private void jBtnWklsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsAlterarActionPerformed

    private void jBtnWklsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
            "Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnWklsExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWklsClientes dialog = new JDlgWklsClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWklsAlterar;
    private javax.swing.JButton jBtnWklsCancelar;
    private javax.swing.JButton jBtnWklsConfirmar;
    private javax.swing.JButton jBtnWklsExcluir;
    private javax.swing.JButton jBtnWklsIncluir;
    private javax.swing.JButton jBtnWklsPesquisar;
    private javax.swing.JComboBox<String> jCboWklsSexo;
    private javax.swing.JCheckBox jChbWklsAtivo;
    private javax.swing.JTextField jFmtWklsCPF;
    private javax.swing.JFormattedTextField jFmtWklsDataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblWklsBairro;
    private javax.swing.JLabel jLblWklsCep;
    private javax.swing.JLabel jLblWklsCpf;
    private javax.swing.JLabel jLblWklsDataDeNascimento;
    private javax.swing.JLabel jLblWklsEmail;
    private javax.swing.JLabel jLblWklsEstado;
    private javax.swing.JLabel jLblWklsIdade;
    private javax.swing.JLabel jLblWklsNome;
    private javax.swing.JLabel jLblWklsNumero;
    private javax.swing.JLabel jLblWklsRg;
    private javax.swing.JLabel jLblWklsRua;
    private javax.swing.JLabel jLblWklsSexo;
    private javax.swing.JLabel jLblWklsTelefone;
    private javax.swing.JSpinner jSpnWklsIdade;
    private javax.swing.JTextField jTxtWklsBairro;
    private javax.swing.JTextField jTxtWklsCep;
    private javax.swing.JTextField jTxtWklsCidade;
    private javax.swing.JTextField jTxtWklsEmail;
    private javax.swing.JTextField jTxtWklsEstado;
    private javax.swing.JTextField jTxtWklsNome;
    private javax.swing.JTextField jTxtWklsNumero;
    private javax.swing.JTextField jTxtWklsRg;
    private javax.swing.JTextField jTxtWklsRua;
    private javax.swing.JTextField jTxtWklsTelefone;
    // End of variables declaration//GEN-END:variables
}
