/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u70791707105
 */
public class JDlgWklsFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgWklsFornecedor
     */
    public JDlgWklsFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setTitle("Cadastro de Fornecedor.");
        setLocationRelativeTo(null);
        jTxtWklsNome.setEnabled(false);
        jTxtWklsEmail.setEnabled(false);
        jTxtWklsBairro.setEnabled(false);
        jTxtWklsRua.setEnabled(false);
        jTxtWklsNumero.setEnabled(false);
        jTxtWklsCidade.setEnabled(false);
        jTxtWklsEstado.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
        jTxtCnpj.setEnabled(false);
        jTxtEmpresa.setEnabled(false);
        jTxtWklsCategoria.setEnabled(false);
        jFmtWklsTelefone.setEnabled(false);
        
    }
    
    public void habilitar(){
        jTxtWklsNome.setEnabled(true);
        jTxtWklsEmail.setEnabled(true);
        jTxtWklsBairro.setEnabled(true);
        jTxtWklsRua.setEnabled(true);
        jTxtWklsNumero.setEnabled(true);
        jTxtWklsCidade.setEnabled(true);
        jTxtWklsEstado.setEnabled(true);
        jBtnWklsCancelar.setEnabled(true);
        jBtnWklsConfirmar.setEnabled(true);
        jTxtCnpj.setEnabled(true);
        jTxtEmpresa.setEnabled(true);
        jTxtWklsCategoria.setEnabled(true);
        jFmtWklsTelefone.setEnabled(true); 
        jBtnWklsIncluir.setEnabled(false);
        jBtnWklsAlterar.setEnabled(false);
        jBtnWklsExcluir.setEnabled(false);
        jBtnWklsPesquisar.setEnabled(false);
    }

    public void desabilitar(){
      jTxtWklsNome.setEnabled(false);
        jTxtWklsEmail.setEnabled(false);
        jTxtWklsBairro.setEnabled(false);
        jTxtWklsRua.setEnabled(false);
        jTxtWklsNumero.setEnabled(false);
        jTxtWklsCidade.setEnabled(false);
        jTxtWklsEstado.setEnabled(false);
        jBtnWklsCancelar.setEnabled(false);
        jBtnWklsConfirmar.setEnabled(false);
        jTxtCnpj.setEnabled(false);
        jTxtEmpresa.setEnabled(false);
        jTxtWklsCategoria.setEnabled(false);
        jFmtWklsTelefone.setEnabled(false);  
         jBtnWklsIncluir.setEnabled(true);
        jBtnWklsAlterar.setEnabled(true);
        jBtnWklsExcluir.setEnabled(true);
        jBtnWklsPesquisar.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtWklsNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtCnpj = new javax.swing.JTextField();
        jTxtWklsCidade = new javax.swing.JTextField();
        jLblWklsNome = new javax.swing.JLabel();
        jLblWklsEstado = new javax.swing.JLabel();
        jTxtWklsNome = new javax.swing.JTextField();
        jTxtWklsEstado = new javax.swing.JTextField();
        jLblWklsRg = new javax.swing.JLabel();
        jTxtWklsCategoria = new javax.swing.JTextField();
        jLblWklsCpf = new javax.swing.JLabel();
        jFmtWklsTelefone = new javax.swing.JTextField();
        jLblWklsEmail = new javax.swing.JLabel();
        jTxtWklsEmail = new javax.swing.JTextField();
        jLblWklsBairro = new javax.swing.JLabel();
        jLblWklsIdade = new javax.swing.JLabel();
        jTxtWklsBairro = new javax.swing.JTextField();
        jLblWklsRua = new javax.swing.JLabel();
        jTxtWklsRua = new javax.swing.JTextField();
        jLblWklsNumero = new javax.swing.JLabel();
        jLblWklsTelefone = new javax.swing.JLabel();
        jTxtEmpresa = new javax.swing.JTextField();
        jBtnWklsCancelar = new javax.swing.JButton();
        jBtnWklsConfirmar = new javax.swing.JButton();
        jBtnWklsPesquisar = new javax.swing.JButton();
        jBtnWklsIncluir = new javax.swing.JButton();
        jBtnWklsAlterar = new javax.swing.JButton();
        jBtnWklsExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtWklsNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNumeroActionPerformed(evt);
            }
        });

        jLabel2.setText("Cidade :");

        jTxtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCnpjActionPerformed(evt);
            }
        });

        jLblWklsNome.setText("Nome :");

        jLblWklsEstado.setText("Estado :");

        jTxtWklsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsNomeActionPerformed(evt);
            }
        });

        jLblWklsRg.setText("Categoria:");

        jTxtWklsCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsCategoriaActionPerformed(evt);
            }
        });

        jLblWklsCpf.setText("Telefone:");

        jLblWklsEmail.setText("Email :");

        jLblWklsBairro.setText("Bairro :");

        jLblWklsIdade.setText("Empresa:");

        jTxtWklsBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsBairroActionPerformed(evt);
            }
        });

        jLblWklsRua.setText("Rua :");

        jTxtWklsRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWklsRuaActionPerformed(evt);
            }
        });

        jLblWklsNumero.setText("Número :");

        jLblWklsTelefone.setText("CNPJ:");

        jBtnWklsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnWklsCancelar.setText("Cancelar");
        jBtnWklsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsCancelarActionPerformed(evt);
            }
        });

        jBtnWklsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnWklsConfirmar.setText("Confirmar");
        jBtnWklsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsConfirmarActionPerformed(evt);
            }
        });

        jBtnWklsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnWklsPesquisar.setText("Pesquisar");
        jBtnWklsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsPesquisarActionPerformed(evt);
            }
        });

        jBtnWklsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnWklsIncluir.setText("Incluir");
        jBtnWklsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsIncluirActionPerformed(evt);
            }
        });

        jBtnWklsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnWklsAlterar.setText("Alterar");
        jBtnWklsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsAlterarActionPerformed(evt);
            }
        });

        jBtnWklsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnWklsExcluir.setText("Excluir");
        jBtnWklsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWklsExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsNome)
                            .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsTelefone)
                            .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsIdade)
                            .addComponent(jTxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jBtnWklsIncluir)
                                .addGap(27, 27, 27)
                                .addComponent(jBtnWklsAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnWklsExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnWklsCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnWklsConfirmar)
                                .addGap(29, 29, 29)
                                .addComponent(jBtnWklsPesquisar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxtWklsNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jTxtWklsBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtWklsRua)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblWklsEstado)
                                        .addGap(105, 105, 105))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtWklsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtWklsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtWklsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblWklsRg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblWklsCpf)
                            .addComponent(jFmtWklsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLblWklsEmail))
                            .addComponent(jTxtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblWklsBairro)
                                .addGap(259, 259, 259)
                                .addComponent(jLblWklsRua))
                            .addComponent(jLblWklsNumero))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsIdade)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblWklsNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtWklsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblWklsRg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtWklsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblWklsCpf)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jFmtWklsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblWklsBairro)
                    .addComponent(jLblWklsRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWklsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblWklsNumero)
                    .addComponent(jLabel2)
                    .addComponent(jLblWklsEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtWklsNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtWklsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnWklsIncluir)
                    .addComponent(jBtnWklsAlterar)
                    .addComponent(jBtnWklsExcluir)
                    .addComponent(jBtnWklsCancelar)
                    .addComponent(jBtnWklsConfirmar)
                    .addComponent(jBtnWklsPesquisar))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtWklsNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNumeroActionPerformed

    private void jTxtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCnpjActionPerformed

    private void jTxtWklsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsNomeActionPerformed

    private void jTxtWklsCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsCategoriaActionPerformed

    private void jTxtWklsBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsBairroActionPerformed

    private void jTxtWklsRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWklsRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWklsRuaActionPerformed

    private void jBtnWklsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsCancelarActionPerformed

    private void jBtnWklsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnWklsConfirmarActionPerformed

    private void jBtnWklsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do Fornecedor:");
    }//GEN-LAST:event_jBtnWklsPesquisarActionPerformed

    private void jBtnWklsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsIncluirActionPerformed

    private void jBtnWklsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnWklsAlterarActionPerformed

    private void jBtnWklsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWklsExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
            "Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnWklsExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgWklsFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgWklsFornecedor dialog = new JDlgWklsFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnWklsAlterar;
    private javax.swing.JButton jBtnWklsCancelar;
    private javax.swing.JButton jBtnWklsConfirmar;
    private javax.swing.JButton jBtnWklsExcluir;
    private javax.swing.JButton jBtnWklsIncluir;
    private javax.swing.JButton jBtnWklsPesquisar;
    private javax.swing.JTextField jFmtWklsTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblWklsBairro;
    private javax.swing.JLabel jLblWklsCpf;
    private javax.swing.JLabel jLblWklsEmail;
    private javax.swing.JLabel jLblWklsEstado;
    private javax.swing.JLabel jLblWklsIdade;
    private javax.swing.JLabel jLblWklsNome;
    private javax.swing.JLabel jLblWklsNumero;
    private javax.swing.JLabel jLblWklsRg;
    private javax.swing.JLabel jLblWklsRua;
    private javax.swing.JLabel jLblWklsTelefone;
    private javax.swing.JTextField jTxtCnpj;
    private javax.swing.JTextField jTxtEmpresa;
    private javax.swing.JTextField jTxtWklsBairro;
    private javax.swing.JTextField jTxtWklsCategoria;
    private javax.swing.JTextField jTxtWklsCidade;
    private javax.swing.JTextField jTxtWklsEmail;
    private javax.swing.JTextField jTxtWklsEstado;
    private javax.swing.JTextField jTxtWklsNome;
    private javax.swing.JTextField jTxtWklsNumero;
    private javax.swing.JTextField jTxtWklsRua;
    // End of variables declaration//GEN-END:variables
}
