/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u70791707105
 */
public class JFrmWklsPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmWklsPrincipal
     */
    public JFrmWklsPrincipal() {
        initComponents();
        setTitle("Sistema de Jogos");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBar = new javax.swing.JMenu();
        jMnuWklsUsuario = new javax.swing.JMenuItem();
        jMnuWklsCliente = new javax.swing.JMenuItem();
        jMnuWklsFornecedor = new javax.swing.JMenuItem();
        jMnuWklsProduto = new javax.swing.JMenuItem();
        jMnuWklsVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuWklsSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuWklsCompra = new javax.swing.JMenuItem();
        jMnuWklsVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar.setMnemonic('c');
        jMenuBar.setText("Cadastro");

        jMnuWklsUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuWklsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuWklsUsuario.setText("Usuário");
        jMnuWklsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsUsuarioActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsUsuario);

        jMnuWklsCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuWklsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuWklsCliente.setText("Cliente");
        jMnuWklsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsClienteActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsCliente);

        jMnuWklsFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuWklsFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMnuWklsFornecedor.setText("Fornecedor");
        jMnuWklsFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsFornecedorActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsFornecedor);

        jMnuWklsProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuWklsProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuWklsProduto.setText("Produto");
        jMnuWklsProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsProdutoActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsProduto);

        jMnuWklsVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMnuWklsVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuWklsVendedor.setText("Vendedor");
        jMnuWklsVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsVendedorActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsVendedor);
        jMenuBar.add(jSeparator1);

        jMnuWklsSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMnuWklsSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuWklsSair.setText("Sair");
        jMnuWklsSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsSairActionPerformed(evt);
            }
        });
        jMenuBar.add(jMnuWklsSair);

        jMenuBar1.add(jMenuBar);

        jMenu2.setMnemonic('m');
        jMenu2.setText("Movimentos");

        jMnuWklsCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuWklsCompra.setText("Compra");
        jMenu2.add(jMnuWklsCompra);

        jMnuWklsVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuWklsVenda.setText("Venda");
        jMnuWklsVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuWklsVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuWklsVenda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuWklsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgWklsUsuario jDlgWklsUsuario = new JDlgWklsUsuario(null, true);
        jDlgWklsUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuWklsUsuarioActionPerformed

    private void jMnuWklsSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuWklsSairActionPerformed

    private void jMnuWklsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsClienteActionPerformed
        // TODO add your handling code here:
        JDlgWklsClientes jDlgWklsClientes = new JDlgWklsClientes(null, true);
        jDlgWklsClientes.setVisible(true);
    }//GEN-LAST:event_jMnuWklsClienteActionPerformed

    private void jMnuWklsVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuWklsVendaActionPerformed

    private void jMnuWklsFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsFornecedorActionPerformed
        // TODO add your handling code here:
         JDlgWklsFornecedor jDlgWklsFornecedor = new JDlgWklsFornecedor(null, true);
        jDlgWklsFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuWklsFornecedorActionPerformed

    private void jMnuWklsProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsProdutoActionPerformed
        // TODO add your handling code here:
         JDlgWklsProdutos jDlgWklsProdutos = new JDlgWklsProdutos(null, true);
        jDlgWklsProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuWklsProdutoActionPerformed

    private void jMnuWklsVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuWklsVendedorActionPerformed
        // TODO add your handling code here:
         JDlgWklsVendedor jDlgWklsVendedor = new JDlgWklsVendedor(null, true);
        jDlgWklsVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuWklsVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmWklsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmWklsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmWklsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmWklsPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmWklsPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuWklsCliente;
    private javax.swing.JMenuItem jMnuWklsCompra;
    private javax.swing.JMenuItem jMnuWklsFornecedor;
    private javax.swing.JMenuItem jMnuWklsProduto;
    private javax.swing.JMenuItem jMnuWklsSair;
    private javax.swing.JMenuItem jMnuWklsUsuario;
    private javax.swing.JMenuItem jMnuWklsVenda;
    private javax.swing.JMenuItem jMnuWklsVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
